astrolabsoftware/fink-utils

fink_utils/photometry/conversion.py
=> Remove condition on the difference between magpsf and magzpsi

fink_utils/hbase/utils.py, fink_utils/photometry/test.py
=> Add utilities for HBase

fink_utils/xmatch/simbad.py
=> Add new types to potential SN host names

fink_utils/__init__.py, fink_utils/xmatch/simbad.py, setup.py
=> Define fallback in case CDS is down

fink_utils/xmatch/simbad.py
=> Add Fail 504 to the white list

fink_utils/__init__.py, fink_utils/broker/distributionUtils.py
=> add the write_to_kafka function from the science_portal

fink_utils/__init__.py, fink_utils/sso/spins.py, fink_utils/sso/utils.py
=> Spin and utilities

fink_utils/__init__.py, fink_utils/sso/spins.py, fink_utils/sso/utils.py
Updated fit for phase curve parameters (R, alpha, delta, H^b, G_1^b, G_2^b). What changed:
- Better error handling
- Better error estimates
- Updated data structure for the output
- Increase test suite
=> Update the spin functions

fink_utils/sso/spins.py
=> Update bounds and p0 for spin and phase parameters

fink_utils/__init__.py, fink_utils/photometry/conversion.py, fink_utils/photometry/vect_conversion.py
Closes #47 
Default is False though
=> Enable flux to be converted in Jansky

fink_utils/__init__.py, fink_utils/sso/spins.py
=> Add the RMS per-band in the SSO payload

fink_utils/__init__.py, fink_utils/photometry/utils.py, run_test.sh
=> New utility for detecting point sources

fink_utils/__init__.py, fink_utils/sso/spins.py
=> [SSO] Add more output parameters to the fit

fink_utils/__init__.py, fink_utils/sso/spins.py
Closes #57 
Spin sign has been flipped.
Variable names and units for the FFT have been homogeneised.
=> [SSO] flip spin sign and homogeneise names

fink_utils/__init__.py, fink_utils/spark/schema_converter.py
=> Add schema_converter from fink-broker

fink_utils/broker/hbaseUtils.py, fink_utils/sso/spins.py
For the release 2023.09 of the SSOFT, two changes:
- `max_phase` has been changed from radians to degrees (to be consistent with others)
- `median_error_phot` has been added, which is the median of the error bar for the lightcurve measurements. Hopefully this would shed more lights on the catastrophic failures we have sometimes.
=> [SSOFT] 2023.09 release

fink_utils/__init__.py, fink_utils/sso/spins.py
=> Least square: use the soft_l1 loss instead of the linear loss

fink_utils/photometry/conversion.py, fink_utils/photometry/vect_conversion.py
=> [Photometry] Handle more cases

fink_utils/spark/utils.py
Related to #66 
Generalise the status check for `valid`, `uppervalid`, and `upper`.
=> Generalise the status check

fink_utils/spark/utils.py
Related to #66 
Optimisation using Spark functions directly.
=> Speed up the filtering by using Spark functions instead of pandas_udf

.github/workflows/run_test.yml, fink_utils/__init__.py, fink_utils/logging/logs.py, fink_utils/slack_bot/bot.py, fink_utils/slack_bot/bot_test.py, requirements.txt, run_test.sh
=> add slack_bot utilities

fink_utils/__init__.py, fink_utils/slack_bot/bot.py, fink_utils/slack_bot/bot_test.py, fink_utils/slack_bot/image.py, fink_utils/slack_bot/msg_builder.py, fink_utils/slack_bot/rich_text/rich_list.py, fink_utils/slack_bot/rich_text/rich_preformatted.py, fink_utils/slack_bot/rich_text/rich_quote.py, fink_utils/slack_bot/rich_text/rich_section.py, fink_utils/slack_bot/rich_text/rich_text.py, fink_utils/slack_bot/rich_text/rich_text_element.py, fink_utils/slack_bot/section.py
=> add a builder to create slack bot message

fink_utils/__init__.py, fink_utils/tg_bot/utils.py
=> Enhance TG bot

.github/workflows/run_test.yml
=> Change the underlying Docker image 

.github/workflows/run_test.yml, fink_utils/tg_bot/utils.py
See e.g. https://github.com/astrolabsoftware/fink-broker/issues/872
=> Add a condition before trying to plot diffmaglim

.github/workflows/run_test.yml, fink_utils/__init__.py, fink_utils/sso/periods.py, fink_utils/sso/profiling/README.md, fink_utils/sso/profiling/run_exp.py, fink_utils/sso/spins.py, fink_utils/sso/utils.py
Closes #82 
Simply:
```python
from fink_utils.sso.periods import extract_period_from_number
ssnamenr = 5209
flavor = "SHG1G2"
period, chi2red = extract_period_from_number(ssnamenr, flavor, Nterms_base=2, period_range=(0.05, 1.2))
```
=> Add new module to fit period

fink_utils/__init__.py, fink_utils/broker/distributionUtils.py, fink_utils/broker/sparkUtils.py
=> Restore deleted files

fink_utils/broker/avroUtils.py
=> Add missing module after refactoring

fink_utils/__init__.py, fink_utils/data/utils.py
=> Add i band in the default filter dictionary

fink_utils/sso/periods.py, fink_utils/sso/spins.py
- Closes #98 
- Closes https://github.com/astrolabsoftware/fink-utils/issues/97
=> Set default oblateness to 0.3

fink_utils/sso/utils.py
=> Add a new parameter to choose the column name for the SSO

fink_utils/__init__.py, fink_utils/sso/spins.py
=> SSOFT: Catch ValueError for least square

fink_utils/tg_bot/utils.py
=> Make better cutout look

fink_utils/sso/spins.py
Closes #110 
Note that `t0` is still fixed (and not fitted).
=> New formula for sidereal period estimation in SSHG1G2

fink_utils/sso/spins.py
=> Fix lower bound for alpha0 for SSHG1G2 model

fink_utils/sso/periods.py, fink_utils/sso/utils.py
=> Factorise code

fink_utils/sso/spins.py
=> SSO: Fix wrong operation

fink_utils/sso/spins.py
=> estimate a/b and a/c from residuals and oblateness

fink_utils/tg_bot/utils.py
=> Fix bug when getting cutouts from API

fink_utils/spark/utils.py
Closes #127 
Extend valid measurements with the last upper limit for each band
Notes
-----
The extended time-series can have:
1. new measurements in r & g
2. new measurements in r or g
3. no new measurements
In the case of (2) or (3), missing addition means: 
- the history already starts with a valid measurement
- the band has no measurements
in which case there is nothing to be further added. Example of an addition in `r` only:
```
ZTF19aavdzci
cjd  cfid    cmagpsf  csigmapsf  cdiffmaglim
0   2.460597e+06     2        NaN        NaN    19.587799
1   2.460597e+06     1        NaN        NaN    19.269800
2   2.460598e+06     1        NaN        NaN    19.552401
3   2.460599e+06     2        NaN        NaN    19.640499
4   2.460599e+06     1        NaN        NaN    19.153601
5 …
```
=> Add utility to extend lc

fink_utils/spark/utils.py
Add last faint limit for AL/SNIa feature extraction.
=> add fainter limits only

fink_utils/spark/utils.py
=> Fix type for onlyfainterlimits

fink_utils/sso/utils.py
=> [SSOFT] Replace name by UID when writing temporary files

fink_utils/sso/utils.py
=> Turn all arguments of subprocess as strings

fink_utils/sso/periods.py, fink_utils/sso/spins.py
=> Set lower boundary for H

fink_utils/sso/periods.py, fink_utils/tg_bot/utils.py
Closes #149 
- more options to `get_curve`
- new utility to send simple tg message
=> Add more options to telegram utilities

fink_utils/tg_bot/utils.py
=> Fix syntax when filtering for NaN and None

fink_utils/tg_bot/utils.py
=> Cast to arrays

.github/workflows/run_test.yml, fink_utils/cutouts/utils.py, fink_utils/slack_bot/bot_test.py, requirements.txt, run_test.sh
=> Update the CI with the new ZTF image

fink_utils/sso/ephem.py, fink_utils/sso/ssoft.py, fink_utils/sso/utils.py
=> Rolling ephemerides computation

fink_utils/sso/ssoft.py
=> Fix wrong join for ephemerides

fink_utils/sso/ephem.py, fink_utils/sso/miriade.py
=> Miriade interface improvements

fink_utils/xmatch/simbad.py
Solving [Issue174](https://github.com/astrolabsoftware/fink-utils/issues/174)
From the issue:
- missing Galaxies/groups are added 
- Some are new syntax and not added.
Thanks,
=> missing galaxies or group of galaxies

fink_utils/sso/miriade.py
=> get_miriade: Make withecl False by default

fink_utils/sso/ephem.py
=> Enable change of observer and shift for ephemerides

fink_utils/tg_bot/utils.py
=> Do not trigger cutout addition if cutout is None. 

fink_utils/tg_bot/utils.py
I am terribly sorry but here is one more trivial fix for that small piece of code
=> Fix sending cutout as an external url
